Repository nhn-academy/eggplant-delivery, pull requests merged in 2022-08, with the labels that each got.

#14 Receiver 설정 오류 수정
  pom.xml
  src/main/java/com/nhnacademy/eggplantdelivery/config/AuthenticationConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/mapper/GenericMapper.java
  src/main/java/com/nhnacademy/eggplantdelivery/mapper/impl/DeliveryInfoMapper.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Receiver.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
Labels: feat, fix, refactor

#16 feat: Swagger 설정 추가
  pom.xml
  src/main/java/com/nhnacademy/eggplantdelivery/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: feat

#17 refactor: 엔티티 컬럼 추가
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/OrderInfoDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
Labels: refactor

#19 운송장 번호로 배송정보 전송
  pom.xml
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/DeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/impl/DefaultDeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/OrderInfoRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/response/DeliveryInfoResponseDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/Location.java
  src/main/java/com/nhnacademy/eggplantdelivery/mapper/GenericMapper.java
  src/main/java/com/nhnacademy/eggplantdelivery/mapper/impl/DeliveryInfoMapper.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Receiver.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/DeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
Labels: feat

#24 운송장 번호 추가 테스트 코드 및 JavaDoc 작성
  pom.xml
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/DeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/impl/DefaultDeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/AuthenticationConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/SwaggerConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/SecureKeyResponseDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/OrderInfoRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/Location.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/status/Status.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Receiver.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/UuidGenerator.java
  src/main/java/com/nhnacademy/eggplantdelivery/repository/DeliveryInfoRepository.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/DeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
  src/test/java/com/nhnacademy/eggplantdelivery/EggplantDeliveryApplicationTests.java
  src/test/java/com/nhnacademy/eggplantdelivery/controller/DeliveryControllerTest.java
  src/test/java/com/nhnacademy/eggplantdelivery/module/UuidGeneratorTest.java
  src/test/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryServiceTest.java
Labels: test, docs

#29 profile 분리, DB 설정
  src/main/java/com/nhnacademy/eggplantdelivery/config/DataSourceConfig.java
  src/main/resources/application.yml
Labels: feat

#30 배송 상태 수정
  src/main/java/com/nhnacademy/eggplantdelivery/EggplantDeliveryApplication.java
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/DeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/impl/DefaultDeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/DeliveryInfoStatusRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/DeliveryStatusUpdateRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/status/Status.java
  src/main/java/com/nhnacademy/eggplantdelivery/exception/DeliveryInfoNotFoundException.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Receiver.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdelivery/repository/DeliveryInfoRepository.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/DeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
Labels: feat, refactor

#33 Queue 생성 및 기존 exchange와 binding 설정
  src/main/java/com/nhnacademy/eggplantdelivery/config/RabbitmqConfig.java
Labels: feat

#39 Repository 테스트 추가
  pom.xml
  src/test/java/com/nhnacademy/eggplantdelivery/repository/DeliveryInfoRepositoryImplTest.java
Labels: test

#37 Controller 테스트 추가
  src/test/java/com/nhnacademy/eggplantdelivery/controller/DeliveryControllerTest.java
Labels: test

#41 fix: delivery-batch 프로젝트로 repository 관련 처리 이동
  pom.xml
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/DeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/SwaggerConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/exception/DeliveryInfoNotFoundException.java
  src/main/java/com/nhnacademy/eggplantdelivery/repository/CustomDeliveryRepository.java
  src/main/java/com/nhnacademy/eggplantdelivery/repository/DeliveryInfoRepository.java
  src/main/java/com/nhnacademy/eggplantdelivery/repository/DeliveryInfoRepositoryImpl.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/DeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
  src/test/java/com/nhnacademy/eggplantdelivery/controller/DeliveryControllerTest.java
  src/test/java/com/nhnacademy/eggplantdelivery/repository/DeliveryInfoRepositoryImplTest.java
  src/test/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryServiceTest.java
Labels: fix

#43 feat: field validation 처리 및 에러처리
  pom.xml
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/DeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/ExceptionController.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/DeliveryInfoStatusRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/DeliveryStatusUpdateRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/OrderInfoRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/response/DeliveryInfoResponseDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/response/DeliveryInfoStatusResponseDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/Location.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Receiver.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
Labels: feat

#45 github action CD 구축
  .github/workflows/maven.yml
  pom.xml
  src/main/java/com/nhnacademy/eggplantdelivery/config/AuthenticationConfig.java
  src/main/resources/application.yml
Labels: feat

#48 feat: README 추가
  README.md
Labels: feat

#50 feat: 쇼핑몰 서버와의 연결 테스트
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/impl/DefaultDeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/CreatedTrackingNoDto.java
  src/main/resources/application.yml
Labels: feat

#52 개인정보 암호화 고도화
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/impl/DefaultDeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/AuthenticationConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/CreatedTrackingNoDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/DeliveryStatusUpdateRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/OrderInfoRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/response/DeliveryInfoResponseDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/exception/DecodeFailureException.java
  src/main/java/com/nhnacademy/eggplantdelivery/exception/EncodeFailureException.java
  src/main/java/com/nhnacademy/eggplantdelivery/exception/FindSecretDataFromSecureKeyManagerException.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/utill/AesGenerator.java
  src/main/java/com/nhnacademy/eggplantdelivery/utill/UuidGenerator.java
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryServiceTest.java
  src/test/java/com/nhnacademy/eggplantdelivery/utill/UuidGeneratorTest.java
Labels: feat, test, refactor, style

#54 queue 추가(배송 상태 변경), 배송 상태 변경시 쇼핑몰에 상태 변경 상황 전송
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/DeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/impl/DefaultDeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/AuthenticationConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/DataSourceConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/constant/ExchangeConstant.java
  src/main/java/com/nhnacademy/eggplantdelivery/constant/QueueConstant.java
  src/main/java/com/nhnacademy/eggplantdelivery/constant/RoutingKeyConstant.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/DeliveryInfoStatusRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/DeliveryStatusUpdateRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/OrderInfoRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/response/DeliveryInfoResponseDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/response/DeliveryInfoStatusResponseDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
  src/main/java/com/nhnacademy/eggplantdelivery/exception/FindSecretDataFromSecureKeyManagerException.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Receiver.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/DeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/utill/AesGenerator.java
  src/test/java/com/nhnacademy/eggplantdelivery/controller/DeliveryControllerTest.java
  src/test/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryServiceTest.java
Labels: feat, fix, refactor

#56 운송장 번호로 배송 정보 조회
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/DeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/AuthenticationConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/constant/ExchangeConstant.java
  src/main/java/com/nhnacademy/eggplantdelivery/constant/QueueConstant.java
  src/main/java/com/nhnacademy/eggplantdelivery/constant/RoutingKeyConstant.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/ExceptionController.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/response/DeliveryLocationResponseDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/Location.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Receiver.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdelivery/repository/CustomDeliveryInfoRepository.java
  src/main/java/com/nhnacademy/eggplantdelivery/repository/DeliveryInfoRepository.java
  src/main/java/com/nhnacademy/eggplantdelivery/repository/DeliveryInfoRepositoryImpl.java
  src/main/java/com/nhnacademy/eggplantdelivery/repository/LocationRepository.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/DeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/utill/AesGenerator.java
  src/test/java/com/nhnacademy/eggplantdelivery/controller/DeliveryControllerTest.java
  src/test/java/com/nhnacademy/eggplantdelivery/repository/DeliveryInfoRepositoryImplTest.java
  src/test/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryServiceTest.java
Labels: feat, test, chore, refactor

#61 feat: Consumer 에러시 DLX 처리
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/impl/DefaultDeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/constant/QueueConstant.java
  src/main/java/com/nhnacademy/eggplantdelivery/constant/RoutingKeyConstant.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Receiver.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/DeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
  src/test/java/com/nhnacademy/eggplantdelivery/controller/DeliveryControllerTest.java
  src/test/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryServiceTest.java
Labels: feat

#64 배송 상태 변경 내용을 쇼핑몰 서버에 전달하기 위한 작업
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/DeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/impl/DefaultDeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/response/DeliveryInfoStatusResponseDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/response/DeliveryLocationResponseDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/exception/DecodeFailureException.java
  src/main/java/com/nhnacademy/eggplantdelivery/exception/EncodeFailureException.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Receiver.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/DeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
Labels: feat

#66 feat: dto에 운송장 번호 요청시 응답 대상이 되는 host를 추가
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/impl/DefaultDeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/AuthenticationConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/OrderInfoRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Receiver.java
  src/main/java/com/nhnacademy/eggplantdelivery/repository/DeliveryInfoRepositoryImpl.java
  src/main/java/com/nhnacademy/eggplantdelivery/repository/LocationRepository.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/utill/AesGenerator.java
  src/test/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryServiceTest.java
Labels: feat, fix

#68 chore: yml 프로파일 분리
  src/main/java/com/nhnacademy/eggplantdelivery/adaptor/impl/DefaultDeliveryAdaptor.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/OrderInfoRequestDto.java
  src/main/resources/application.yml
  src/test/java/com/nhnacademy/eggplantdelivery/EggplantDeliveryApplicationTests.java
Labels: chore
