Repository nhn-academy/eggplant-delivery, pull requests merged in 2022-07, with the labels that each got.

#4 feat: RabbitMQ 설정 및 설정 민감 정보 암호화
  pom.xml
  src/main/java/com/nhnacademy/eggplantdelivery/EggplantDeliveryApplication.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/AuthenticationConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/SecureKeyResponseDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/Location.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/github-action.p12
Labels: feat

#8 fix: 엔티티 컬럼 추가 #1
  src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
Labels: fix

#10 Sender 구현
  src/main/java/com/nhnacademy/eggplantdelivery/config/RabbitmqConfig.java
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/dto/request/OrderInfoRequestDto.java
  src/main/java/com/nhnacademy/eggplantdelivery/entity/DeliveryInfo.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Sender.java
Labels: feat

#13 refactor: receiver 구현 수정
  src/main/java/com/nhnacademy/eggplantdelivery/controller/DeliveryController.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Receiver.java
  src/main/java/com/nhnacademy/eggplantdelivery/module/Sender.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/DeliveryService.java
  src/main/java/com/nhnacademy/eggplantdelivery/service/impl/DefaultDeliveryService.java
Labels: fix, refactor
